addSbtPlugin("com.github.sbt"   % "sbt-native-packager" % "1.9.9")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"        % "2.4.6")
addSbtPlugin("io.spray"         % "sbt-revolver"        % "0.9.1")
addSbtPlugin("ch.epfl.scala"    % "sbt-scalafix"        % "0.9.34")
addSbtPlugin("com.dwijnand"     % "sbt-dynver"          % "4.1.1")
addSbtPlugin("com.timushev.sbt" % "sbt-updates"         % "0.6.2")
